In [2]:
!python -m pip install numpy


[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
k=np.array([[1,2,3],[4,5,6]])
k

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
k=([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])
k

[[3, 8, 4], [9, 3, 5], [11, 15, 17], [19, 31, 8]]

In [6]:
k=np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])
k

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [7]:
m=np.array([[4,8,7],[3,1,5],[6,9,13]])
m

array([[ 4,  8,  7],
       [ 3,  1,  5],
       [ 6,  9, 13]])

In [45]:
#m=np.array([[4,8,7],[3,1,5],[6,9,13]],[[41,81,71],[31,11,51],[61,91,131]])
m

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [10]:
m=np.array([[[4,41],[8,81],[7,71]],[[3,31],[1,11],[5,51]],[[6,61],[9,91],[13,131]]])
m

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [11]:
m.shape

(3, 3, 2)

In [12]:
k[1][0] #indexing or other is slicing

9

In [13]:
k[1,0] #subscripting

9

In [14]:
k[2]

array([11, 15, 17])

In [15]:
k[2,0:3:1] #[starting:ending+1:gape]

array([11, 15, 17])

In [16]:
k[2,:]

array([11, 15, 17])

In [17]:
k[:,1]

array([ 8,  3, 15, 31])

In [18]:
k[:,1:2]

array([[ 8],
       [ 3],
       [15],
       [31]])

In [19]:
m[0:2,1:3]

array([[[ 8, 81],
        [ 7, 71]],

       [[ 1, 11],
        [ 5, 51]]])

In [20]:
k[0:2,1:3]

array([[8, 4],
       [3, 5]])

In [21]:
m[:2,-2:,:1]

array([[[8],
        [7]],

       [[1],
        [5]]])

In [22]:
m[2:3,1:3]

array([[[  9,  91],
        [ 13, 131]]])

In [23]:
m[-1:,-2:,:]

array([[[  9,  91],
        [ 13, 131]]])

In [24]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
a[0,0]=7
a[0,1]=8
a[0,2]=9
a

array([[7, 8, 9],
       [4, 5, 6]])

In [26]:
a[:,1]=[69,96]
a

array([[ 7, 69,  9],
       [ 4, 96,  6]])

In [27]:
a+10
a

array([[ 7, 69,  9],
       [ 4, 96,  6]])

In [28]:
a+10

array([[ 17,  79,  19],
       [ 14, 106,  16]])

In [29]:
a

array([[ 7, 69,  9],
       [ 4, 96,  6]])

In [30]:
np.append(a,[[1,1,1]],axis=0) #row

array([[ 7, 69,  9],
       [ 4, 96,  6],
       [ 1,  1,  1]])

In [34]:
np.append(a,[[2],[2]],axis=1)

array([[ 7, 69,  9,  2],
       [ 4, 96,  6,  2]])

In [44]:
'''np.array()
np.arange()
np.linspace()
np.ones()
np.zeros()
np.eye()
np.random.randint()
'''


'np.array()\nnp.arange()\nnp.linspace()\nnp.ones()\nnp.zeros()\nnp.eye()\nnp.random.randint()\n'

In [36]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
list(range(11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [38]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [42]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
print(np.ones((4,5),dtype=int))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
p=